version: '2'

networks:
  test:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
          gateway: 172.30.0.1

services:
  openvpn:
    image: your-repo.local/openvpn:0.0.1-SNAPSHOT
    hostname: openvpn
    container_name: openvpn
    extends:
      file: common-service.yml
      service: log-restart
    ports:
      - your.ip.address.here:1194:1194/udp
    cap_add:
      - NET_ADMIN
    environment:
      - NX_IP=172.30.0.22
      - NX_PORT=8888
    networks:
      test:
        ipv4_address: 172.30.0.23
    volumes:
      - vpn_conf_dir:/etc/openvpn
      - ssl_conf_dir:/etc/openssl/openvpn/ca

volumes:
  #enviroment
  vpn_conf_dir:
  ssl_conf_dir:
